name: monorepos
publish_to: none
environment:
  sdk: ^3.7.2

workspace:
  - app
  - config
  - shared
  - core/design_system
  - core/network
  - core/utilities
  - core/localization

melos:
  packages:
    - app
    - core/**
    - packages/**
    - shared
    - config

  scripts:
    build_runner:
      run: melos exec -- "dart run build_runner build"
      packageFilters:
        dependsOn:
          - "build_runner"

  command:
    bootstrap:
      environment:
        sdk: ^3.7.2
        flutter: ">=1.17.0"
      dependencies:
        flutter_svg: ^2.1.0
        google_fonts: ^6.2.1
        envied: ^1.1.1
        intl: any
        dio: ^5.8.0+1
        logger: ^2.5.0

      dev_dependencies:
        flutter_lints: ^5.0.0
        envied_generator: ^1.1.1
        build_runner: ^2.4.15

dev_dependencies:
  melos: ^7.0.0-dev.8
