name: network
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  logger: ^2.5.0

  shared:
    path: ../../shared

  config:
    path: ../../config

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
